# Generated by Django 5.2.14 on 2026-05-31 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_api', '0001_initial'),
        ('sync_1c', '0015_alter_item_item_type_alter_item_organization_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='sync_1c.organization', verbose_name='Организация'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('user', 'item', 'organization')},
        ),
    ]
