# Generated by Django 5.2.14 on 2026-05-31 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_api', '0002_alter_cartitem_unique_together_cartitem_organization_and_more'),
        ('sync_1c', '0015_alter_item_item_type_alter_item_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='sync_1c.organization', verbose_name='Организация'),
        ),
    ]
