# Generated by Django 5.2.14 on 2026-06-03 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_api', '0003_alter_cartitem_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('telegram_username', models.CharField(blank=True, max_length=150, null=True, verbose_name='Юзернейм в TG')),
                ('tg_first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя в TG')),
                ('tg_last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Фамилия в TG')),
                ('tg_photo_url', models.URLField(blank=True, max_length=1024, null=True, verbose_name='Ссылка на аватарку TG')),
                ('tg_language_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Язык в TG')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_account', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь Django')),
            ],
            options={
                'verbose_name': 'Telegram аккаунт',
                'verbose_name_plural': 'Telegram аккаунты',
            },
        ),
    ]
