# Generated by Django 5.2.14 on 2026-09-11 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_api', '0004_telegramaccount'),
        ('sync_1c', '0033_itemimage_is_invalid_orderitem_package_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='sync_1c.itempackage', verbose_name='Упаковка'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12, verbose_name='Количество (базовых единиц)'),
        ),
    ]
