# Generated by Django 5.2.14 on 2026-09-15 08:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_api', '0005_cartitem_package_alter_cartitem_quantity'),
        ('sync_1c', '0034_itempackage_guid_1c'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('package__isnull', False)), fields=('user', 'item', 'organization', 'package'), name='cartitem_unique_packaged_line'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('package__isnull', True)), fields=('user', 'item', 'organization'), name='cartitem_unique_base_line'),
        ),
    ]
