# Generated by Django 5.2.14 on 2026-09-21 06:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_api', '0006_cartitem_line_per_unit'),
        ('sync_1c', '0035_order_checkout_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActReconciliationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guid_partner1c', models.CharField(max_length=255, verbose_name='GUID контрагента 1С')),
                ('date_from', models.DateField(verbose_name='Период с')),
                ('date_to', models.DateField(verbose_name='Период по')),
                ('status', models.CharField(choices=[('pending', 'Ожидает 1С'), ('ready', 'Готов'), ('failed', 'Ошибка')], db_index=True, default='pending', max_length=20, verbose_name='Статус')),
                ('file', models.FileField(blank=True, null=True, upload_to='acts/', verbose_name='Файл акта')),
                ('filename', models.CharField(blank=True, default='', max_length=255, verbose_name='Имя файла')),
                ('message', models.CharField(blank=True, default='', max_length=500, verbose_name='Сообщение 1С')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменена')),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='Клиент уведомлён в Telegram')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='act_requests', to='sync_1c.organization', verbose_name='Организация')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='act_requests', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заявка на акт сверки',
                'verbose_name_plural': 'Заявки на акт сверки',
                'ordering': ['-created_at'],
            },
        ),
    ]
