# Generated by Django 5.2.14 on 2026-05-22 16:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный Идентификатор 1С')),
                ('sku', models.CharField(blank=True, max_length=100, null=True, verbose_name='Артикул')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Номенклатура (Товар)',
                'verbose_name_plural': 'Номенклатура (Товары)',
            },
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный Идентификатор 1С')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Вид номенклатуры',
                'verbose_name_plural': 'Виды номенклатуры',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный Идентификатор 1С')),
                ('inn', models.CharField(max_length=12, verbose_name='ИНН')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='PriceType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный Идентификатор 1С')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('currency', models.CharField(default='UZS', max_length=10, verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Вид цены',
                'verbose_name_plural': 'Виды цен',
            },
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='Уникальный Идентификатор 1С')),
                ('image_path', models.CharField(max_length=512, verbose_name='Путь к файлу картинки')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главная картинка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sync_1c.item', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Картинка товара',
                'verbose_name_plural': 'Картинки товаров',
                'ordering': ['-is_main', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='sync_1c.itemtype', verbose_name='Вид номенклатуры'),
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Цена')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления цены')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='sync_1c.item', verbose_name='Товар')),
                ('price_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='sync_1c.pricetype', verbose_name='Вид цены')),
            ],
            options={
                'verbose_name': 'Цена из прайс-листа',
                'verbose_name_plural': 'Прайс-листы (Цены)',
                'unique_together': {('item', 'price_type')},
            },
        ),
    ]
