# Generated by Django 5.2.14 on 2026-05-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_1c', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='inn',
            field=models.CharField(max_length=13, null=True, verbose_name='ИНН'),
        ),
    ]
