# Generated by Django 5.2.14 on 2026-05-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_1c', '0003_userprofile_inn'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='period',
            field=models.DateTimeField(null=True, verbose_name='Период'),
        ),
    ]
