# Generated by Django 5.2.14 on 2026-05-24 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_1c', '0004_pricelist_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='period',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Период (Дата установки в 1С)'),
        ),
    ]
