# Generated by Django 5.2.14 on 2026-05-30 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sync_1c', '0005_alter_pricelist_period'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='sku',
            new_name='articul',
        ),
    ]
