# Generated by Django 5.2.14 on 2026-05-31 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_1c', '0008_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Скидка'),
        ),
    ]
