# Generated by Django 5.2.14 on 2026-05-31 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_1c', '0009_orderitem_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number_1c',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер в 1С'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cancellation_reason',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Причина отмены'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_canceled',
            field=models.BooleanField(default=False, verbose_name='Отменено'),
        ),
    ]
