# Generated by Django 5.2.14 on 2026-05-31 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_1c', '0010_order_order_number_1c_orderitem_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Остаток')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='sync_1c.item', verbose_name='Товар')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_stocks', to='sync_1c.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Остаток товара',
                'verbose_name_plural': 'Остатки товаров',
                'unique_together': {('item', 'organization')},
            },
        ),
    ]
