# Generated by Django 5.2.14 on 2026-05-31 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_1c', '0011_itemstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='sync_1c.organization', verbose_name='Организация'),
        ),
    ]
