# Generated by Django 5.2.14 on 2026-05-31 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sync_1c', '0012_pricelist_organization'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pricelist',
            unique_together={('item', 'price_type', 'organization')},
        ),
    ]
