# Generated by Django 5.2.14 on 2026-05-31 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_1c', '0013_alter_pricelist_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sync_1c.organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='itemtype',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_types', to='sync_1c.organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='order',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='sync_1c.organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='pricetype',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_types', to='sync_1c.organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='sync_1c.organization', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='itemstock',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_stocks', to='sync_1c.organization', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='organization',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='sync_1c.organization', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='inn',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
