# Generated by Django 5.2.14 on 2026-05-31 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_1c', '0014_item_organization_itemtype_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sync_1c.itemtype', verbose_name='Вид номенклатуры'),
        ),
        migrations.AlterField(
            model_name='item',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sync_1c.organization', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='itemstock',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_stocks', to='sync_1c.organization', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_types', to='sync_1c.organization', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='order',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='sync_1c.organization', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='sync_1c.organization', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='pricetype',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_types', to='sync_1c.organization', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='sync_1c.organization', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='price_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='sync_1c.pricetype', verbose_name='Тип цен'),
        ),
    ]
