# Generated by Django 5.2.14 on 2026-05-31 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_1c', '0015_alter_item_item_type_alter_item_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='prefix',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Уникальный префикс (slug)'),
        ),
    ]
