# Generated by Django 5.2.14 on 2026-06-01 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_1c', '0016_organization_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='price_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_organizations', to='sync_1c.pricetype', verbose_name='Тип цен для анонимных пользователей'),
        ),
    ]
