# Generated by Django 5.2.14 on 2026-06-01 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sync_1c', '0017_organization_price_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricelist',
            name='period',
        ),
    ]
