# Generated by Django 5.2.14 on 2026-06-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_1c', '0018_remove_pricelist_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='support_phone',
            field=models.CharField(default='', max_length=15, verbose_name='Телефон служба поддержки'),
        ),
    ]
