# Generated by Django 5.2.14 on 2026-06-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_1c', '0019_organization_support_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='image_path',
            field=models.ImageField(max_length=512, upload_to='products/', verbose_name='Файл картинки'),
        ),
    ]
