# Generated by Django 5.2.14 on 2026-06-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_1c', '0020_alter_itemimage_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Telegram ID'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Юзернейм в TG'),
        ),
    ]
