# Generated by Django 5.2.14 on 2026-06-03 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_1c', '0021_userprofile_phone_userprofile_telegram_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='telegram_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='telegram_username',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('accepted', 'Подтвержден'), ('changed', 'Изменен'), ('blocked', 'Отменен')], default='new', max_length=20, verbose_name='Статус аккаунта'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
