# Generated by Django 5.2.14 on 2026-06-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_1c', '0023_remove_userprofile_status_userprofile_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='telegram_bot_token',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Токен Telegram бота'),
        ),
    ]
