# Generated by Django 5.2.14 on 2026-07-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_1c', '0024_organization_telegram_bot_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата последней синхронизации'),
        ),
        migrations.AddField(
            model_name='itemstock',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата последней синхронизации'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['organization', 'name'], name='sync_1c_ite_organiz_aa9fa7_idx'),
        ),
    ]
