# Generated by Django 5.2.14 on 2026-07-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_1c', '0025_item_updated_at_itemstock_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='price_type',
        ),
        migrations.AddField(
            model_name='pricelist',
            name='is_retail',
            field=models.BooleanField(default=False),
        ),
    ]
