# Generated by Django 5.2.14 on 2026-07-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_1c', '0026_remove_organization_price_type_pricelist_is_retail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricelist',
            name='is_retail',
        ),
        migrations.AddField(
            model_name='pricetype',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
