# Generated by Django 5.2.14 on 2026-07-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_1c', '0027_remove_pricelist_is_retail_pricetype_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='instagram',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Instagram (ссылка или @username)'),
        ),
        migrations.AlterField(
            model_name='pricetype',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='По умолчанию'),
        ),
    ]
