# Generated by Django 5.2.14 on 2026-07-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_1c', '0028_organization_instagram_alter_pricetype_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='guid_partner1c',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='GUID контрагента 1С'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Наименование контрагента'),
        ),
    ]
