# Generated by Django 5.2.14 on 2026-07-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_1c', '0029_userprofile_guid_partner1c_alter_userprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='unregistered_notice',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Сообщение незарегистрированному клиенту'),
        ),
    ]
