# Generated by Django 5.2.14 on 2026-09-11 08:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_1c', '0032_itemtype_is_invalid'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemimage',
            name='is_invalid',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Недействительна (не показывать на сайте)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='package_count',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Количество упаковок'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='package_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='ID упаковки в 1С'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='package_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Упаковка'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='package_ratio',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12, verbose_name='Базовых единиц в упаковке'),
        ),
        migrations.CreateModel(
            name='ItemPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный Идентификатор 1С')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование упаковки')),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=12, verbose_name='Базовых единиц в упаковке')),
                ('is_default', models.BooleanField(default=False, verbose_name='Выбрана по умолчанию')),
                ('is_invalid', models.BooleanField(db_index=True, default=False, verbose_name='Недействительна (не показывать на сайте)')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='sync_1c.item', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Упаковка товара',
                'verbose_name_plural': 'Упаковки товаров',
                'ordering': ['quantity', 'name'],
            },
        ),
    ]
