# Generated by Django 5.2.14 on 2026-09-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_1c', '0034_itempackage_guid_1c'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Комментарий клиента'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Желаемая дата отгрузки'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cashless', 'Безналичный расчет'), ('cash', 'Наличные'), ('transfer', 'Перевод'), ('deferred', 'Отсрочка платежа')], default='', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
