"""
Django settings for qarshi_backend project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
def _env_bool(name, default=False):
    """os.getenv возвращает строку, поэтому "False" превращалось в True. Парсим честно."""
    return os.getenv(name, str(default)).strip().lower() in ("1", "true", "yes", "on")

DEBUG = _env_bool("DEBUG", False)

# Хосты берём из .env; по умолчанию — боевой домен. Пробелы вокруг значений срезаем.
ALLOWED_HOSTS = [h.strip() for h in os.getenv("ALLOWED_HOSTS", "qarshi1s.uz,.qarshi1s.uz").split(",") if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'django_filters',
    'sync_1c',
    'front_api',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'front_api.utils.DebugURLMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'qarshi_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'qarshi_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        'HOST': os.getenv("DB_HOST", "localhost"),
        'PORT': os.getenv("DB_PORT", "5432"),
        'NAME': os.getenv("DB_NAME", "qarshi_db"),
        'USER': os.getenv("DB_USER", "bakhraaam"),
        'PASSWORD': os.getenv("DB_PASSWORD", "Cjiobapbaq1"),
    }
}

# LANGUAGE_CODE = 'en-us'
# TIME_ZONE = 'UTC'
# USE_I18N = True
# USE_TZ = True

#языковый
LANGUAGE_CODE = 'ru-ru'
USE_I18N = True

#часовой
TIME_ZONE = 'Asia/Tashkent'
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# URL-префикс, по которому картинки будут доступны в браузере и во Flutter
MEDIA_URL = '/media/'
# Абсолютный путь в файловой системе вашего сервера, куда физически будут сохраняться файлы
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# --- Кэш (Redis) ---
# URL берём из .env; если Redis недоступен/не задан — падать не должно, поэтому
# при пустом REDIS_URL используем локальный in-memory кэш (dev/тесты без Redis).
REDIS_URL = os.getenv("REDIS_URL", "redis://127.0.0.1:6379/1")
if REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": REDIS_URL,
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        }
    }

# Время жизни кэша каталога (сек). Инвалидация мгновенная — по версии на организацию.
CATALOG_CACHE_TTL = int(os.getenv("CATALOG_CACHE_TTL", "300"))

# Настройки времени жизни JWT токенов
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),     # Access токен будет жить 1 день
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),   # Refresh токен будет жить 30 дней
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
}

# --- CORS / CSRF: боевой домен qarshi1s.uz ---
# Точный origin основного фронтенда
CORS_ALLOWED_ORIGINS = [
    "https://qarshi1s.uz",
]
# Поддомены организаций вида avto.qarshi1s.uz
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://[a-zA-Z0-9_-]+\.qarshi1s\.uz$",
]

# Django admin / POST-формы по HTTPS на этом домене
CSRF_TRUSTED_ORIGINS = [
    "https://qarshi1s.uz",
    "https://*.qarshi1s.uz",
    "http://avto.localhost:57586",
]

if DEBUG:
    # Локальная разработка: localhost и ngrok-туннели
    CORS_ALLOWED_ORIGIN_REGEXES += [
        r"^http://localhost:\d+$",
        r"^http://127\.0\.0\.1:\d+$",
        r"^http://[a-zA-Z0-9_-]+\.localhost:\d+$",
        r"^https://[a-zA-Z0-9_-]+\.ngrok-free\.(app|dev)$",
    ]
    
    CSRF_TRUSTED_ORIGINS += [
        "http://127.0.0.1:8001",
        "http://localhost:57586",
        "http://localhost:8001",
    ]

else:
    # Продакшн за HTTPS-прокси (nginx): доверяем заголовку и защищаем куки
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True